application:
  env:
    name: dev

spring:
  cloud:
    gcp:
      bigquery:
        datasetName: DS2
        project-id: jason-hsbc

server:
  port: 8080

service:
  clientid: 912156613264-0ecti69s7mv650490ghoskuqv3c6ofim.apps.googleusercontent.com
  allow:
    account: terraform@jason-hsbc.iam.gserviceaccount.com, jason1.pan@maplequad.com